### ISSUE TITLE
Errore 3ds 

### ISSUE THREAD

**Issue by Taverz** [wwwhttpru/flutter_yookassa_sdk#2]
[Presentation] Attempt to present <UINavigationController: 0x123048800> on <YooKassaPayments.SheetViewController: 0x122825e00> (from <YooKassaPayments.PaymentMethodsViewController: 0x11f97f640>) whose view is not in the window hierarchy.

**Comment by Taverz** [comment]
Swift IOS

**Comment by Taverz** [comment]
FlutterYookassaViewController
---------

    public func startConfirmationProcess(
        confirmationUrl: String,
        paymentMethodType: PaymentMethodType,
        completionHandler: @escaping ResultCompletionHandler
    ) {
        self.resultCompletionHandler = completionHandler
        if (self.tokenizationViewController != nil && self.tokenizationViewController is TokenizationModuleInput) {
            (self.tokenizationViewController as! TokenizationModuleInput)
                .startConfirmationProcess(
                    confirmationUrl: confirmationUrl,
                    paymentMethodType: paymentMethodType
                )
        } else {
            self.resultCompletionHandler?(Result.failure(.on3dsConfirmNotFound))
        }
    }
    --------------------
---Errore
     if (self.tokenizationViewController != nil && self.tokenizationViewController is TokenizationModuleInput) {
            (self.tokenizationViewController as! TokenizationModuleInput)

**Comment by wwwhttpru** [comment]
Спасибо. В ближайшее время (1-2 дня) займусь исходом проблемы.

---

Thank you. In the near future (1-2 days) I will solve the problem.

**Comment by Taverz** [comment]
Здравствуйте. Нашли решение проблемы? Мне очень надо, поскорее решить эту проблему. Спасибо, что уделили внимание.

**Comment by wwwhttpru** [comment]
Здравствуйте, решение проблемы уже в процессе. В ближайшие часы появится обновление пакета.

**Comment by wwwhttpru** [comment]
Исправлено в версии 0.1.2

---

Fixed in version 0.1.2

**Comment by Taverz** [comment]
Спасибо!
