### ISSUE TITLE
google pay won't turn off

### ISSUE THREAD

**Issue by Taverz** [wwwhttpru/flutter_yookassa_sdk#4]
when you try to remove from all google play in the end he remained

**Comment by wwwhttpru** [comment]
Если вы хотите удалить Google Pay полностью из оплаты, добавьте следующие строки в ваш AndroidManifest.

---

If you want to remove Google Pay completely from payment, add the following lines to your AndroidManifest.

```xml
<manifest ... xmlns:tools="http://schemas.android.com/tools">
...
<meta-data
    android:name="com.google.android.gms.wallet.api.enabled"
    tools:node="remove" />
...
</manifest>
```

**Comment by wwwhttpru** [comment]
Если вы хотите пользователю не предоставлять способ оплаты Google Pay, настройте ваш **PaymentMethodTypes**.

----

If you don't want the user to provide a Google Pay payment method, configure your **PaymentMethodTypes**.

```dart
      tokenizationSettings: TokenizationSettings(
        ....
        paymentMethodTypes: PaymentMethodTypes(
          rawValue: {
            PaymentMethodType.bankCard,
            PaymentMethodType.yooMoney,
          },
        ),
        ...
      ),
```
